def edit_distance(s: str, t: str, maxdiff: int = ...) -> int: ...

class WFAWrapper:
    def __init__(
        self, 
        bandwidth: int = ...
        ): ...
    def align(
        self, 
        text: str = ..., 
        pattern: str = ..., 
        state: int = ...) -> int: ...