from collections import namedtuple
from typing import Dict, Iterable, Optional, Tuple, List, Iterator

Variant = namedtuple("Variant", "position allele scores")

class Read:
    def __init__(
        self,
        name: Optional[str] = ...,
        mapq: int = ...,
        source_id: int = ...,
    ): ...
    @property
    def mapqs(self) -> Tuple[int]: ...
    @property
    def name(self) -> str: ...
    @property
    def source_id(self) -> int: ...
    def __iter__(self) -> Iterator[Variant]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, key: int) -> Variant: ...
    def __setitem__(self, index: int, variant: Variant): ...
    def __contains__(self, position: int) -> bool: ...
    def add_variant(self, position: int, scores: Iterable[float]) -> None: ...
    def add_haplotag(self, hp: str) -> None: ...
    def add_phaseset(self, ps: int) -> None: ...
    def add_mapq(self, mapq: int) -> None: ...
    def sort(self) -> None: ...
    def is_sorted(self) -> bool: ...
    
class ReadSet:
    def add(self, read: Read) -> None: ...
    def __iter__(self) -> Iterator[Read]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, key: int) -> Read: ...
    def subset(self, reads_to_select: Iterable[int]) -> ReadSet: ...
    def assign_selection_status(self, reads_to_select: Iterable[int]) -> None: ...
    def get_positions(self) -> List[int]: ...

class GenotypeLikelihoods:
    def __init__(self, gl: Iterable[float], num_alleles: int = ...): ...
    def __getitem__(self, index: int) -> float: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[float]: ...
    def __eq__(self, other) -> bool: ...
    
def binomial_coefficient(n: int, k: int) -> int: ...

class Genotype:
    def __init__(self, alleles: List[int]): ...
    def is_none(self) -> bool: ...
    def get_index(self) -> int: ...
    def as_vector(self) -> List[int]: ...
    def get_ploidy(self) -> int: ...
    def __eq__(self, other) -> bool: ...
    def __ne__(self, other) -> bool: ...
    def __lt__(self, other) -> bool: ...

def get_max_genotype_ploidy() -> int: ...
def get_max_genotype_alleles() -> int: ...

class GenotypingAlgorithm:
    def __init__(
        self,
        readset: ReadSet,
        n_haplotypes: int,
        ploidy: int,
        temperature: float,
        recombrate: float,
        eff_pop_size: float,    
        num_sampled_haplotypes: int,
        remove_reference_path: bool,
        sampling_eff_pop_size: float,
        allele_penalty: int,
        positions: Iterable[int] = ...,
        n_allele_positions: Iterable[int] = ...,
        allele_references: Iterable[Iterable[int]] = ...,
        is_sv: Iterable[bool] = ...,
    ): ...
    def get_genotype_likelihoods(self, pos: int, nr_allele: int) -> GenotypeLikelihoods: ...

def run_cpp_tests() -> None: ...